clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 50

    # The number of clients selected in each round
    per_round: 5

    # Should the clients compute test accuracy locally?
    do_test: false

server:
    address: 127.0.0.1
    port: 8000
    random_seed: 1
    simulate_wall_time: true

data: !include mnist_noniid.yml

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 50

    # The target accuracy
    target_accuracy: 0.97

    # The machine learning model
    model_name: lenet5

    # Number of epoches for local training in each communication round
    epochs: 10
    batch_size: 32
    optimizer: SGD

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    model:
        num_classes: 10

    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0

    average_duration: 13.52
    unqualified_ratio: 0.5
